"use client";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { Provider } from "react-redux";
import { store } from "@/store/store";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Header from "@/components/Header";
import SideContent from "@/components/SideContent";
import { useState } from "react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [showFull, setShowFull] = useState(false);
  return (
    <html lang="en">
      <Provider store={store}>
        <body className={inter.className}>
          <Header setShowFull={setShowFull} showFull={showFull} />
          <main className="flex h-[calc(100vh-60px)]  overflow-hidden">
            <aside
              className={`${
                showFull
                  ? "-translate-x-[400px] w-0"
                  : "w-[260px] translate-x-0   h-full p-4"
              } transition-all duration-500 border-r  hidden md:block overflow-auto `}
            >
              <SideContent />
            </aside>
            <aside className="flex-1  overflow-auto">{children}</aside>
          </main>
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
        </body>
      </Provider>
    </html>
  );
}
